---
- hosts: all 
  gather_facts: yes    
  roles:
    - linux-system-roles.cockpit    
- hosts: all
  any_errors_fatal: true
  gather_facts: yes
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:        
    - name: create users
      import_tasks: tasks/create-user.yaml
    - name: install artifactory certificates
      import_tasks: tasks/install-artifactorty-certificates.yaml 


- hosts: portainer_agent   
  any_errors_fatal: true
  gather_facts: yes
  tasks:        
    - import_tasks: tasks/install-portainer-agent.yaml
    
    
- hosts: portainer 
  any_errors_fatal: true
  gather_facts: yes
  tasks:        
    - import_tasks: tasks/install-portainer.yaml 
    - import_tasks: tasks/add-agent-endpoints.yaml   




    
   
