---
- hosts: all
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker
  tasks:        
    - name: create users
      import_tasks: tasks/create-user.yaml
    - name: install artifactory certificates
      import_tasks: tasks/install-artifactorty-certificates.yaml 


- hosts: portainer_agent   
  tasks:        
    - import_tasks: tasks/install-portainer-agent.yaml
    
    
- hosts: portainer   
  tasks:        
    - import_tasks: tasks/install-portainer.yaml 
    - import_tasks: tasks/add-agent-endpoints.yaml    



    
   
