---
    - name: Create {{deployments_user}} user
      no_log: true
      user:
        name: "{{deployments_user}}"
        # encrypt the password  
        # python -c 'import crypt; print(crypt.crypt("This is my Password", "$1$SomeSalt$"))'
        password: "{{deployments_user_password}}"
        shell: /bin/bash
        groups: wheel
        append: yes
      become: yes  
    - name: Set {{deployments_user}} user public key
      authorized_key:
        user: "{{deployments_user}}"
        state: present
        key: "{{ lookup('file', '/home/pakr/.ssh/id_rsa.pub') }}"
