---
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
        
    - name: Install ca-certificates
      yum:
        name: ca-certificates
        state: latest   
    
    - name: copy artifactory certs
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: './resources/docker-artifactory.matrixapps.com/cacert.crt', dest: '/etc/pki/ca-trust/source/anchors/cacert.crt' }
        - { src: './resources/docker-artifactory.matrixapps.com/cacert.pem', dest: '/etc/pki/ca-trust/source/anchors/cacert.pem' }
        - { src: './resources/docker-artifactory.matrixapps.com/Intermediate.crt', dest: '/etc/pki/ca-trust/source/anchors/Intermediate.crt' }
    
    - name: Install ca-certificates
      command: update-ca-trust        
      become: yes 
      
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
      
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
    - name: Add {{deployments_user}} user to docker group
      user:
        name: "{{deployments_user}}"
        groups: docker
        append: yes
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      
