---        
    - name: Run portainer agent
      docker_container:
        name: portainer-agent
        image: portainer/agent:1.5.1
        restart_policy: always
        state: started
        ports:
          - "9001:9001"
        volumes:
           - /var/run/docker.sock:/var/run/docker.sock
           - /var/lib/docker/volumes:/var/lib/docker/volumes
        env:
          AGENT_SECRET: "{{portainer_agent_key}}"
          
