---        
    - name: create portainer config dir
      file:
        path: /etc/portainer
        state: directory

    - name: Create portainer key file
      #no_log: true    
      copy:
        content: "{{portainer_admin_password}}"
        dest: /etc/portainer/key
    
    - name: Create portainer volume
      docker_volume:
        name: portainer_data 
      
    - name: Run portainer
      no_log: true    
      docker_container:
        name: portainer
        image: portainer/portainer:1.23.2
        restart_policy: always
        state: started
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
           - "/var/run/docker.sock:/var/run/docker.sock"
           - "/etc/portainer/key:/etc/portainer/key"
           - "portainer_data:/data"
        env:
          AGENT_SECRET: "{{portainer_agent_key}}"
        command: >
            --admin-password-file /etc/portainer/key      
            
