---    
    - name: Create mongo config files directory
      file:
       path: "{{config_files_dir}}"
       state: directory
       owner: "{{deployments_user}}"
       group: "{{deployments_user}}"       
       mode: '0700'      
       
    - name: Install pip repository
      yum:
        name: epel-release
        state: latest  
        
    - name: Install pip
      yum:
        name: python-pip
        state: latest 
        
    - name: Install docker sdk
      pip:
        name: docker-py
        state: latest 
        
    - name: Install py mongo
      pip:
        name: pymongo
        state: latest 

    - name: Copy mongo key file
      copy:
        src: './resources/keyfile'
        dest: "{{config_files_dir}}/keyfile"
        owner: 999
        group: 999
        mode: '0400'

    - name: Create docker volume for mongo data
      docker_volume:
        name: mongo-data
       
    - name: Run mongo container
      docker_container:
        name: mongo
        image: mongo:4.0.12
        restart_policy: "unless-stopped"
        volumes:
          -  "mongo-data:/data/db/"
          - "{{config_files_dir}}/keyfile:/opt/highgate/etc/keyfile"
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: "admin"
          MONGO_INITDB_ROOT_PASSWORD: "password"
        command: "--replSet rs0 --keyFile /opt/highgate/etc/keyfile"
  
    - name: Initialize an empty list for our strings
      set_fact:
        my_strings: []
      
    - name: Initialize an empty list for our strings
      set_fact:
        my_strings: "{{my_strings + [hostvars[item].ansible_host  + ':27017']}}"
      with_items: "{{groups.mongo}}"      

    - debug: var=my_strings     
      
    - name: Ensure replicaset rs0 exists
      mongodb_replicaset:
        login_host: "{{ hostvars[inventory_hostname].ansible_host }}"
        login_user: admin
        login_password: password
        replica_set: rs0
        members: "{{my_strings}}"
      when: groups.mongo.index(inventory_hostname) == 0

      
      
