---
    - name: remove portainer
      docker_container:
        name: portainer
        state: absent 
      
    - name: remove portainer volume
      docker_volume:
        name: portainer_data 
        state: absent
